### ISSUE TITLE
[Resource Pack] Dark Amethyst

### ISSUE THREAD

**Issue by R-Y-M-R** [melkypie/resource-packs#144]
<img src="https://i.imgur.com/UpSewwL.png"><br/>

# Dark Amethyst :black_heart: :purple_heart:

A theme for OSRS/runelite by R-Y-M-R.

## Credit to Levy for Spacenation edition :blue_heart: and iawhd for the original :black_heart: version. :purple_heart: :purple_heart: :purple_heart:

[Download](https://github.com/R-Y-M-R/dark-amethyst-osrs-resource-pack/releases) the source.zip and read [how to use a custom pack (not from the hub)](https://github.com/melkypie/resource-packs/wiki/Using-a-custom-pack-%28not-from-the-hub%29).

Give your Runelite client an Amethyst vibe. 

<img src="https://i.imgur.com/rnAF8Xw.png"><br/>

<img src="https://i.imgur.com/3opqxcV.png"><br/>

**Comment by nickyGyul** [comment]
Check the wiki to get your pack to be available to upload: 
https://github.com/melkypie/resource-packs/wiki/Submitting-a-Resource-pack-to-the-Hub-using-GitHub-Desktop

Basically resubmit the pull request but choose `pack-dark-amethyst` as the base instead of `master`. For some reason when I changed the base into your desired branch name it closed your pull request.

**Comment by melkypie** [comment]
Follow the guide what @nickyGyul posted. The reason your previous pull request did not work is due to you branching off of master. If you follow the guide precisely, you should not have any issues submitting your pack. Closing this issue, if you need anymore support do it on discord as I would like to keep Github Issues for pack requests and bugs/enhancements.
