### ISSUE TITLE
Issues with custom resource pack.

### ISSUE THREAD

**Issue by tuqqy** [melkypie/resource-packs#92]
Hi, I'm having issues enabling a custom resource pack. I did very simple editing on the login screen and the chatbox (making them darker) just to get an understanding of how it works after I replaced the updated images I next copy the path (under downloads. same as in the example) and am unable to paste it into resource path pack 1. I am unable to right click so I typed out the path and nothing has happened. I tried restarting runelite, resetting resource packs and turning on/off plugins. Help!!

**Comment by melkypie** [comment]
Usually this is because the path is wrong. It should point to path where you can see the login_screen and the other folders and leaving out the trailing /. Also you can CTRL+C and then CTRL+V in the settings. If you are still having issues I suggest you join the [discord](https://discord.com/invite/DsDhUz4NNN) as it is hard to troubleshoot support issues here.
